### ISSUE TITLE
Search retrieves no results

### ISSUE THREAD

**Issue by apricot23** [nika-begiashvili/kodi-adjaranet#1]
Search has stopped retrieving results for me. It also appears like the desktop site has changed, maybe this is related?

**Comment by alexandrius** [comment]
@apricot23 Pretty much that. Pull requests are appreciated

**Comment by alexandrius** [comment]
Just reviewed Adjara's changes:

This is simple docs for new logic:

//Search
https://api.adjaranet.com/api/v1/search-advanced?movie_filters%5Bwith_actors%5D=3&movie_filters%5Bwith_directors%5D=1&movie_filters%5Bkeyword%5D=prison&movie_filters%5Byear_range%5D=1900%2C2019&movie_filters%5Binit%5D=true&filters%5Btype%5D=movie&keywords=prison&page=1&per_page=5&source=adjaranet

//Details
https://api.adjaranet.com/api/v1/movies/1000155?filters%5Bwith_directors%5D=3&source=adjaranet


//Data
https://api.adjaranet.com/api/v1/movies/878410710/season-files/1?source=adjaranet

**Comment by apricot23** [comment]
Wish I could be useful but I'm just an Armenian freeloader in the states who can't code. Thanks for this addon
