### ISSUE TITLE
Addon discontinued?

### ISSUE THREAD

**Issue by ThoGru80** [nika-begiashvili/kodi-adjaranet#2]
Hello Nika, I would like to use your add-on, but unfortunately it no longer works?  I see search, I also get results, but I can't play videos!  I use libreelec and we use adjara over the chrome browser but would it be easier for my wife using the gui?  Do you bring out any updates?

**Comment by alexandrius** [comment]
@ThoGru80 If you still get results I think we might be able to fix it

**Comment by ThoGru80** [comment]
I am installing the addon! I start the addon! Only the search is shown to me! I can enter titles in the search and they are shown to me but shown like a folder!

Maybe you can testing and fix this Problem under Kodi 18.9 :) Movies over the search is enough with categroies (example the nextflix addon) would be nice but important is i can start movies over the Kodi GUI ...

I am happy to test the add-on for you if you are interested

I used with Kodi

xstream Addon (german movies)
youtube
Netflix 
TV Tab Addon (for German TV)
Simple TV Client (Georgian TV)

**Comment by ThoGru80** [comment]
![IMG_20210421_053629](https://user-images.githubusercontent.com/81796239/115484418-d5f50a00-a263-11eb-96c2-77270c564573.jpg)
![IMG_20210421_053647](https://user-images.githubusercontent.com/81796239/115484423-d7becd80-a263-11eb-8791-be3d751a3278.jpg)
![IMG_20210421_053705](https://user-images.githubusercontent.com/81796239/115484424-d8576400-a263-11eb-8a3e-f26f32cb18dc.jpg)

**Comment by alexandrius** [comment]
Will look into this on the weekend. But not sure if it's easily fixable

**Comment by ThoGru80** [comment]
ok

**Comment by alexandrius** [comment]
New law has been passed in Georgia. All of the free services will be shut down. No point in fixing this

**Comment by alexandrius** [comment]
@nika-begiashvili Archive the repo
